### ISSUE TITLE
Compatibility with multiple Java versions at the same time

### ISSUE THREAD

**Issue by madoar** [javafxports/openjdk-jfx#141]
As far as I understand the current situation, beginning with Java 11, OpenJFX/JavaFX will be excluded from the JDK.
Additionally, I believe it to be a good idea to be able to add OpenJFX to your projects via maven and co.

This leads me to my question, how and if it's possible to support both Java version 11+ and 10- with a single application/build?

**Comment by kevinrushforth** [comment]
OpenJFX 11 can run on OpenJDK 10 or on JDK 11 (either OpenJDK builds or Oracle JDK builds). If you try to run your application with Oracle JDK 10, it should work, with the javafx.* modules being used from the JDK 10 platform rather than from the openjfx 11 modules pulled in from maven central (the latter will be ignored).
