### ISSUE TITLE
JavaFX documentation lies about DirectX 11

### ISSUE THREAD

**Issue by gregdavisd** [javafxports/openjdk-jfx#160]
Navigate to http://openjdk.java.net/projects/openjfx/

Click "OpenJFX Wiki" -> "Developer Documentation" -> "Get Acquainted with JavaFX Architecture"

https://docs.oracle.com/javase/8/javafx/get-started-tutorial/jfx-architecture.htm#JFXST788

Read:

"
Prism processes render jobs. It can run on both hardware and software renderers, including 3-D. 
...
    DirectX 9 on Windows XP and Windows Vista

    **DirectX 11 on Windows 7**
...
"

I can't find any reference to DX11 in the code (ID3D11Device, ID3D11DeviceContext, etc.). Maybe it means it emulates to DX11 via LibAngle, but the ES2 stack isn't built or shipped by default in the Windows build. Is there a DX11 plugin somewhere? I only see DX9 code.

**Comment by kevinrushforth** [comment]
I'm quite certain that the author of that tutorial doc was not trying to intentionally misrepresent the state of the Prism pipeline, so the title of your bug report was ill-chosen.

In any case, JavaFX does not use DIrectX11, it uses DX 9. Since this tutorial is out of date, I doubt it will be fixed. The only thing we could do as far as OpenJFX goes is to remove the link from our Wiki to that tutorial page, but since most of it is accurate (if old), I don't think that's warranted.

**Comment by johanvos** [comment]
Apart from that DX9/DirectX11 confusion, I consider the referred document pretty ok. Since it is outside of the wiki, I can't edit it.
I would leave the reference to the document, but this is somehow a call to action for creating more up to date articles that can be referred to.
