### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by aalmiray** [javafxports/openjdk-jfx#21]
There's a `.hgignore` file at the root but no corresponding `.gitignore` file.

**Comment by bourgesl** [comment]
Maybe just copy .hgignore to .gitignore ?

**Comment by aalmiray** [comment]
Not really, no. The .hgignore file explicitly ignores .gitignore 😏 and there are other settings that no longer make sense.
The #22 PR addresses this issue.

**Comment by kevinrushforth** [comment]
I (almost) got bit by the lack of a .gitignore file when I somewhat carelessly did a "git add ." (never a good idea I know, but still would be nice to exclude the most common build files), so I'll take this issue.

This issue should be decoupled from any changes related to IDE files (e.g., issue #22 )

The .gitignore file is specific to the GitHub mirror and wouldn't need to back upstream (just like the .ci and .git directories are only in the sandbox). Conversely, any changes to IDE files would need to be done to address an upstream JBS issue, just like any other bug fix / enhancement.

Also, creating a .gitignore file, so that build artifacts, etc. are ignored, is independent of any proposed changes to the IDE configuration files.
