### ISSUE TITLE
Cross Compile jfx-11 branch for Arm Fails

### ISSUE THREAD

**Issue by dellgreen** [javafxports/openjdk-jfx#269]
Hi chaps,

Build file '/home/ubuntu/sdks/openjfx/IwOpenJfx11/submodules/openjdk-jfx/build.gradle' line: 1579

* What went wrong:
A problem occurred configuring project ':swing'.
> Exception thrown while executing model rule: PublishingPluginRules#publishing(ExtensionContainer)
   > Could not get unknown property 'moduleEmptyPublicationJarArmv6hf' for task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

If i change to master branch then the sdk task completes successfully. 
Is it the intention that we should be able to build from jfx-11 branch and fixes will be back ported from master? or should we be always building from master branch?

**Comment by kevinrushforth** [comment]
It really depends on what you are trying to do. In general, developers should use the "develop" branch (or the "master" branch), which always has the latest fixes. This is currently for openjfx12 development.

The jfx-11 branch is a stable branch specifically for openjfx 11.x releases and is not a general development branch. Some fixes will be backported to 11.x, with approval. @johanvos can provide a more complete answer, especially about what sort of fixes he plans to backport to 11.x.

**Comment by dellgreen** [comment]
Ok many thanks for the quick response.
I'm currently in the process of upgrading our openjdk + openjfx for armv6hf runtime to java 11.
I successfully have a  build of the  jmods for openjdk 11, so have now moved on to openjfx.
I started with the jfx-11 branch as will be running openjfx on openjdk 11, but this fails to build. 

Is the aim that the master branch will run as a minimum on openjdk 11? 
I assume that this could change going forward, and a working Arm build of jfx-11 is the sensible branch to target once its fixed?

Also i don't see any jmods for the armv6hf-sdk  build, is it a case that its a work in progress an not finished yet?  :)

**Comment by johanvos** [comment]
Note that we have an 11-ea build for armv6hf at https://gluonhq.com/products/javafx/ (bottom of the page).

The fix for your current issue in the develop branch is here: https://github.com/javafxports/openjdk-jfx/commit/f01ddc7ebfab87ccd89dba08ee503bb086753f3b#diff-c197962302397baf3a4cc36463dce5ea

While this can easily be backported to jfx-11, there is more work to do in the embedded build. The ea-build is working fine on e.g. Raspberry Pi systems where you want to use the framebuffer (see https://gluonhq.com/javafx-11-early-access-on-embedded/) but if you want it to work out of the box on X11 based systems, some manual work is needed.
Ultimately, a single launch property should be enough for switching between fb or X11, but the Monocle code that handles this needs some cleanup.

Are you looking for fb support, or X11 mainly?

**Comment by dellgreen** [comment]
Excellent thanks, I just feed fb support.

**Comment by dellgreen** [comment]
Using '-Dembedded=monocle -Dglass.platform=Monocle' seems to be the required options to help javafx11 get further in the startup which are not required for javafx10, i hit a new error, but will explore this further and report in new ticket.
With respects to this ticket moving from jdk-11 branch to master branch fixed the problem for embedded.

**Comment by dellgreen** [comment]
For anyone interested: I was successful in creating jmods for arm using the previous method of passing the openjfx modular sdk artifact to openjdk build using the  import-modules method to the ./configure script

**Comment by eugener** [comment]
Can this ticket be closed?

**Comment by dellgreen** [comment]
Yes it can. For anyone else trying to build arm version, the solution at the time of writing was to build using the  master branch which contained fixes to allow successful build.

**Comment by dellgreen** [comment]
also cherry-picking f01ddc7ebfab87ccd89dba08ee503bb086753f3b into jfx-11 branch as recommended also works
