### ISSUE TITLE
Support FFmpeg 4.0 (libavcodec/libavformat v58)

### ISSUE THREAD

**Issue by klausenbusk** [javafxports/openjdk-jfx#335]
OpenJFX should be updated to support a newer version of FFmpeg. A lot of distributions is already shipping with FFmpeg 4.0> (Ubuntu 18.10, Debian Buster, Archlinux ..).

**Comment by klausenbusk** [comment]
Upstream (?) issue: https://bugs.openjdk.java.net/browse/JDK-8215894

**Comment by kevinrushforth** [comment]
Yes, this is a known issue, and is already tracked in JBS as [JDK-8215894](https://bugs.openjdk.java.net/browse/JDK-8215894).

As a workaround, try installing the older libavformat57.

**Comment by klausenbusk** [comment]
> Yes, this is a known issue, and is already tracked in JBS as [JDK-8215894](https://bugs.openjdk.java.net/browse/JDK-8215894).

Sorry for the noise then, the two issue tracker approach did confuse me a bit, but I got it now.

**Comment by acorupe** [comment]
I see this issue has been fixed, however the fix is available in OpenJFX 13 and unfortunately I require it for Embedded armv6hf, and embedded OpenJFX 13 is not available at this time. Will this fix be pushed back to OpenJFX 11 or 12 and available for embedded? Or any idea when embedded might be available for OpenJFX 13?
