### ISSUE TITLE
NPE in MenuButtonSkinBase class

### ISSUE THREAD

**Issue by vlaaad** [javafxports/openjdk-jfx#465]
This is a duplicate of [JDK-8179097](https://bugs.openjdk.java.net/browse/JDK-8179097).
We are getting reports from users experiencing this issue on openjfx-12: https://github.com/defold/editor2-issues/issues/2572

I can't reproduce it myself, but looking at the code there is only one place where this exception can come from:
```
Platform.runLater(() -> Utils.removeMnemonics(popup, getSkinnable().getScene()));
```
`getSkinnable()` can return `null` when skin is disposed (this happens when MenuBar's items change — see `MenuBarSkin::rebuildUI`, and that happens in our app). 
Are you interested in a PR with speculative fix for this (saving skinnable's scene to local variable and using that variable in lambda)?

**Comment by vlaaad** [comment]
Bump! We keep getting reports from our users about it (https://github.com/defold/editor2-issues/issues/2624). @kevinrushforth is anyone watching this issue tracker?

**Comment by kevinrushforth** [comment]
We do look at this issue tracker, but mainly to see whether there is a new bug that we weren't aware of. I did miss your comment:

> Are you interested in a PR with speculative fix for this (saving skinnable's scene to local variable and using that variable in lambda)?

Ideally we would want to see a test that fails without the fix and passes with the fix. I realize that this might be a case where it's hard (because of timing) to come with a test that provokes the bug consistently, so we could consider a fix without a regression test, provided you can show that it is fixing the underlying issue and not just a symptom. And is the right fix to cache the the scene or to add a null check in the lambda (the former seems more correct to me, which is what you suggested, but it's worth asking the question).

If you would like to contribute a fix, please see [CONTRIBUTING.md](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/CONTRIBUTING.md). As noted there, we will need an Oracle Contributor Agreement (OCA) from you.

**Comment by vlaaad** [comment]
Thanks for the answer! 
I agree that there are at least 2 different speculative solutions, so I'll think what is more suitable too. 
Also agree that it's nice to have a repro, will try again to reproduce it.
