### ISSUE TITLE
WebView or WebEngine fails 

### ISSUE THREAD

**Issue by omniprof** [javafxports/openjdk-jfx#588]
OS: Windows 10 Pro 1903
Java: AdoptOpenJDK jdk-11.0.4+11, OpenJDK jdk-12, Oracle 1.8.0_222
Build System: Maven
IDE: NetBeans 11.1

When the sample code is run under Java 1.8 it successfully displays any page I point it at.
Under Java 11 or 12 and using OpenJFX 12 (12.0.2) or 13 (13_ea_13):
Simple Basic HTML:
- Works
google.ca
- A page is displayed but missing many of Google's decorations. If I enter a search term (google auto suggest works) and press return the window closes.
Pretty much every other page on the web such as www.omnijava.com
-Window with a title opens but after a few seconds it closes without any messages or stack trace.

I have numerous JavaFX samples that I use in my courses and this is the only one that will not run on OpenJFX.
[MainApp.java.txt](https://github.com/javafxports/openjdk-jfx/files/3597235/MainApp.java.txt)

**Comment by jperedadnr** [comment]
Could you add your pom.xml file as well?

**Comment by omniprof** [comment]
Attached are my pom files. There is the parent pom that all my demo apps us and then the local pom. I have named them parentpom and localpom.
[parentpom.xml.txt](https://github.com/javafxports/openjdk-jfx/files/3597400/parentpom.xml.txt)
[localpom.xml.txt](https://github.com/javafxports/openjdk-jfx/files/3597403/localpom.xml.txt)

**Comment by jperedadnr** [comment]
Why don't you use the JavaFX Maven plugin instead of Exec? See samples: 
https://github.com/openjfx/samples/tree/master/IDE/NetBeans/Non-Modular/Maven
https://github.com/openjfx/samples/tree/master/IDE/NetBeans/Modular/Maven

Also documented at: https://openjfx.io/openjfx-docs/#IDE-NetBeans

With this plugin, it works fine for me on Mac and Windows, with JavaFX 12 and 13, and your url loads perfectly fine.

Also I recommend using a modular app and `javafx:jlink`, instead of the fat jar. See https://openjfx.io/openjfx-docs/#modular

**Comment by jperedadnr** [comment]
There was this discussion a while ago:https://github.com/javafxports/openjdk-jfx/issues/316. 

Your issue seems to be exactly the same: Exec:java has some issues finding the right webkit native libraries.

See detailed explanation starting at https://github.com/javafxports/openjdk-jfx/issues/316#issuecomment-457854056

So I believe this issue is a duplicate.
