### ISSUE TITLE
Downloadable Javadoc for all of OpenJFX

### ISSUE THREAD

**Issue by odbuser2** [javafxports/openjdk-jfx#599]
When JavaFX was bundled with the JDK, the javadoc zip file provided by Oracle could be used as a reference offline in a browser or in IDE's.

Now that it is unbundled and delivered as separate jars or jmods, this convenience is gone.  This is a request to combine the javadoc from all of OpenJDK into one zip similar to what Oracle did in JDK8 (in JDK9+ it became part of the JDK doc) and make it available on Gluon's site alongside the binary downloads.

While we could independently rebuild the javadoc (I did try but ran into issues), it is not straightforward and provides a barrier of entry that wasn't there before.  Yes, the documentation is available online, but it is more convenient offline when bandwidth, network restrictions, or latency are of a concern.

Please also see my other recent issue concerning the javadoc (and source) jars from maven when used in IDE's (specifically Netbeans).

**Comment by kevinrushforth** [comment]
The build of JavaFX already produces a downloadable `javafx-docs-NN.zip` bundle, so this is a matter of Gluon deciding whether (or not) to host it.

@johanvos or @tiainen could let you know the best place to file this request -- probably somewhere in the https://github.com/openjfx/ -- since there is no change needed in the JavaFX build.

**Comment by tiainen** [comment]
The javadoc is already available as a jar file from the maven central repository. But I've also taken the opportunity to add a direct link to download the javadoc as a zip from the [Gluon JavaFX download page](https://gluonhq.com/javafx).
