### ISSUE TITLE
Ability to force a clean Travis or Appveyor CI build

### ISSUE THREAD

**Issue by kevinrushforth** [javafxports/openjdk-jfx#64]
It looks like the Travis  and Appveyor CI builds are setup to do an incremental build. We should have a way to force a clean build, either via a fresh 'git clone' (or equivalently, running 'git clean -fdx' after a git pull) or by runing 'gradle clean' before the build. I note that cleaning the repo is a more robust solution, but running gradle clean would likely be easier.

The reason I noticed this is that the latest Travis CI build [210.1](https://travis-ci.org/javafxports/openjdk-jfx/jobs/363225122) for PR #61 failed due to repeated warnings about bad class files, which I ran into yesterday locally with incremental builds when changing the classfile format (from JDK 9 to JDK 10 in my case).

**Comment by kevinrushforth** [comment]
@brcolow would this be easy to add?

**Comment by brcolow** [comment]
Hmmmm...do you think it is only setup to do an incremental build because we are caching things? Otherwise it should be a clean, fresh build every time. If it is only the cache that is affecting things, we should be able to add a CLEAR_CACHE environment variable that, well, clears the cache. [Here is the Appveyor cache settings](https://github.com/javafxports/openjdk-jfx/blob/develop/appveyor.yml#L69) and [the Travis CI cache settings](https://github.com/javafxports/openjdk-jfx/blob/develop/.travis.yml#L41). If it is not only the cache that is causing incremental builds, what is it?

**Comment by kevinrushforth** [comment]
I had assumed it was pulling changes into an existing repo (or cloning into an existing directory), but that doesn't seem to be the case. I might be wrong about the problem. I'll look at the log more closely...

**Comment by kevinrushforth** [comment]
I looked more closely, and it seems I mis-diagnosed the problem.

I am marking the issue as "invalid" and closing it.

**Comment by kevinrushforth** [comment]
I will open up a new bug for the issue I am seeing, once I figure out the problem. I suspect it might be related to using a too-old version of gradle, since gradle 4.3 doesn't fully support JDK 10.
