### ISSUE TITLE
Publish standalone jar files to Maven Central

### ISSUE THREAD

**Issue by tiainen** [javafxports/openjdk-jfx#84]
Starting from Java 11, JavaFX will no longer be bundled inside the SDK download. Add support to the gradle build to publish standalone jar files to Maven Central. Developers can then declare dependencies in their projects to include the JavaFX artifacts that they need.

Gradle itself advices to use the [Maven plugin](https://docs.gradle.org/current/userguide/maven_plugin.html) instead of the incubating [Maven Publish plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) when artifacts need to be uploaded to Maven Central.

**Comment by DJViking** [comment]
> Gradle itself advices to use the Maven plugin instead of the incubating Maven Publish plugin when artifacts need to be uploaded to Maven Central.

That has now changed in the upcoming Gradle 4.8
https://docs.gradle.org/4.8-rc-1/release-notes.html
> The maven-publish and ivy-publish plugins are now considered stable and use of the maven plugin is discouraged as it will eventually be deprecated — please migrate.

**Comment by tiainen** [comment]
Ok, that implies that the version for the gradle wrapper needs to be upgraded as well? I'm not sure what the policy is with regard to that. We probably need to upgrade eventually if we want to be able to run the build with Java 11.

**Comment by kevinrushforth** [comment]
There is already a JBS issue to upgrade to gradle 4.8 (which is needed for JDK 11 support). It is being tracked in JBS as [JDK-8201553](https://bugs.openjdk.java.net/browse/JDK-8201553). I will update gradle wrapper at the same time.

Do you have any insight as to when gradle 4.8 will be published?

**Comment by DJViking** [comment]
Gradle 4.8 was released on June 4th.

**Comment by tiainen** [comment]
Maven publication is being worked on in PR #83 and is using the new Maven Publish plugin.

**Comment by johanvos** [comment]
Apart from the Windows fileAlreadyExists issue, everything is fixed. That issue seems unrelated to checksums, as either the file exists with a different checksum and is deleted; or nothing is done. So even if the checksum calculation is wrong, the file is only copied to after either `f.exists()` is false or after `f.delete()` is executed. It might be that `f.delete()` is returning false, although I thought that was only possible if f is a directory, otherwise an `IOException` would be thrown.

As for the empty jars: this is required in order to allow maven projects not specifying the platform. In maven, we can depend on e.g. javafx.media without specifying which platform we are on. That will download the empty jar (ignored) and the associated pom file that will have a dependency on the platform-specific jar file (containing module-info, classes and native libs).

**Comment by kevinrushforth** [comment]
Windows will not let you delete a file in use, but it does seems strange that no error is thrown when attempting to delete the file.

In any case, I can confirm that the checksums are not working on any platform. If you run two applications (either concurrently or sequentially), the files will be recreated each time. On the other two platforms, deleting the file out from under a running application might (or might not) cause errors. On Windows, it is fatal. I'll take a quick look at it later this morning, but if you want to take this as a separate bug so as not to delay getting this in, that seems fine to me.

Thanks for the explanation of the empty jars. I had suspected something like that.

**Comment by kevinrushforth** [comment]
I see why there is no exception when the file cannot be deleted. File.delete does not throw an exception on failure, but returns a boolean indicating success or failure (and without any further information). Files.delete does throw IOE, so maybe that would be a better method to use? If I replace `f.delete()` with `Files.delete(f.toPath())` it throws the exception as one might expect.

**Comment by johanvos** [comment]
I'll have a look at the checksum issue

**Comment by kevinrushforth** [comment]
OK. I did a quick look, printing the hashes, and the fileHash matches the output of running md5sum on the file, so that looks correct. isHash doesn't match.

**Comment by kevinrushforth** [comment]
Also, you have trailing white-space in two files. This will need to be eliminated.

```
modules/javafx.web/src/main/java/com/sun/webkit/perf/WCFontPerfLogger.java
modules/javafx.web/src/test/java/test/javafx/scene/web/MathMLRenderTest.java
```

**Comment by kevinrushforth** [comment]
Sorry...that comment was meant for another PR.

**Comment by tiainen** [comment]
As it is not easily feasible to generate separate javadocs for each module, I will take the following pragmatic approach: publish each javafx module artifact with the entire javadoc jar (which is about 10mb). I'm of course open to other ideas.

**Comment by kevinrushforth** [comment]
I can't think of a better plan in the short term. Longer term, we could consider adding an option to enable building of the separate per-module javadocs, but then you would lose the hyperlinks from, e.g., javafx.controls to types in javafx.graphics and javafx.base.

**Comment by tiainen** [comment]
That was indeed the issue I ran into. But fixing that requires more changes than editing just the build.gradle file.

**Comment by DJViking** [comment]
Is the artifactId name finalised?
Shouldn't artifactId be javafx-controls, instead of javafx.controls?
Currently they are same as the module name. This seems odd though for an
artifactId  I have never seen any dependencies that used punctuation as
delimiter in artifactId, but the more usual dash delimiter.


Den ons. 27. jun. 2018 kl. 23:40 skrev Joeri Sykora <
notifications@github.com>:

**Comment by kevinrushforth** [comment]
I don't have an opinion on whether the artifactId should exactly match the module name or whether replacing `.` with `-` in the artifactId would make more sense.

**Comment by eugener** [comment]
I can confirm that the standard for maven artifact names is to use `-` (dash) .
In some cases `_`(underscore) is used to separate special attributes, which might work well for platform names in our case.  Here is a good example using `scala-xml` library definition:
```
<dependency>
     <groupId>org.scala-lang.modules</groupId>
     <artifactId>scala-xml_2.12</artifactId>
     <version>1.0.6</version>
</dependency>
```

**Comment by johanvos** [comment]
The question is: do we want to follow the standard of the Java Module System, or the standard for maven.
It seems to me the standard for naming Java modules is more strict (because of the link with package naming) where the "standard" for maven is not really a standard, just common usage.
But I have no strong preference.

**Comment by johanvos** [comment]
After discussing with a number of experts in jigsaw and maven deployment, it seems better indeed to decouple the module name from the maven artifactId.

**Comment by kevinrushforth** [comment]
I think this issue can be closed, unless you want to keep it open until the final release (GA) of openjfx 11.

**Comment by tiainen** [comment]
I left this open because it wasn't clear at first how far we would integrate the entire process into the existing gradle build setup. What we have now is a build that can generate jar files that can be published as maven artifacts. The actual publication has been left out and is part of the automated build jobs.
